"""update db

Revision ID: 1ed6c48a7ca8
Revises: 2359ba00f1c5
Create Date: 2021-07-10 10:07:44.286931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ed6c48a7ca8'
down_revision = '2359ba00f1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_user_extra_info', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'db_user_extra_info', 'db_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'db_user_extra_info', type_='foreignkey')
    op.drop_column('db_user_extra_info', 'user_id')
    # ### end Alembic commands ###
