"""update db

Revision ID: 2359ba00f1c5
Revises: 8929b363f36d
Create Date: 2021-07-10 09:53:33.054061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2359ba00f1c5'
down_revision = '8929b363f36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_user_extra_info', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('db_user_extra_info', sa.Column('middle_name', sa.String(), nullable=True))
    op.add_column('db_user_extra_info', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('db_user_extra_info', sa.Column('dob', sa.String(), nullable=True))
    op.add_column('db_user_extra_info', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_user_extra_info', 'gender')
    op.drop_column('db_user_extra_info', 'dob')
    op.drop_column('db_user_extra_info', 'last_name')
    op.drop_column('db_user_extra_info', 'middle_name')
    op.drop_column('db_user_extra_info', 'first_name')
    # ### end Alembic commands ###
