"""init db

Revision ID: 588cca5b1c70
Revises: ca85dbb1e5c2
Create Date: 2021-07-03 21:52:23.586554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '588cca5b1c70'
down_revision = 'ca85dbb1e5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_user_created_at'), 'db_user', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_user_deleted'), 'db_user', ['deleted'], unique=False)
    op.create_index(op.f('ix_db_user_email'), 'db_user', ['email'], unique=True)
    op.create_index(op.f('ix_db_user_full_name'), 'db_user', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_user_full_name'), table_name='db_user')
    op.drop_index(op.f('ix_db_user_email'), table_name='db_user')
    op.drop_index(op.f('ix_db_user_deleted'), table_name='db_user')
    op.drop_index(op.f('ix_db_user_created_at'), table_name='db_user')
    op.drop_table('db_user')
    # ### end Alembic commands ###
