"""update db

Revision ID: 6482823da8b3
Revises: 6ffed7292def
Create Date: 2024-10-09 16:11:52.430625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6482823da8b3'
down_revision = '6ffed7292def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_item',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_item_created_at'), 'db_item', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_item_deleted'), 'db_item', ['deleted'], unique=False)
    op.create_index(op.f('ix_db_item_description'), 'db_item', ['description'], unique=False)
    op.create_index(op.f('ix_db_item_title'), 'db_item', ['title'], unique=False)
    op.create_table('db_user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_user_created_at'), 'db_user', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_user_deleted'), 'db_user', ['deleted'], unique=False)
    op.create_index(op.f('ix_db_user_email'), 'db_user', ['email'], unique=True)
    op.create_index(op.f('ix_db_user_username'), 'db_user', ['username'], unique=True)
    op.create_table('db_user_profile',
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('following', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['db_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_user_profile_created_at'), 'db_user_profile', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_user_profile_deleted'), 'db_user_profile', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_user_profile_deleted'), table_name='db_user_profile')
    op.drop_index(op.f('ix_db_user_profile_created_at'), table_name='db_user_profile')
    op.drop_table('db_user_profile')
    op.drop_index(op.f('ix_db_user_username'), table_name='db_user')
    op.drop_index(op.f('ix_db_user_email'), table_name='db_user')
    op.drop_index(op.f('ix_db_user_deleted'), table_name='db_user')
    op.drop_index(op.f('ix_db_user_created_at'), table_name='db_user')
    op.drop_table('db_user')
    op.drop_index(op.f('ix_db_item_title'), table_name='db_item')
    op.drop_index(op.f('ix_db_item_description'), table_name='db_item')
    op.drop_index(op.f('ix_db_item_deleted'), table_name='db_item')
    op.drop_index(op.f('ix_db_item_created_at'), table_name='db_item')
    op.drop_table('db_item')
    # ### end Alembic commands ###
