"""update db

Revision ID: 68d0b8738895
Revises: c7a3ca9a96f9
Create Date: 2021-07-10 09:49:50.502245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68d0b8738895'
down_revision = 'c7a3ca9a96f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_user_extra_info',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_user_extra_info_created_at'), 'db_user_extra_info', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_user_extra_info_deleted'), 'db_user_extra_info', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_user_extra_info_deleted'), table_name='db_user_extra_info')
    op.drop_index(op.f('ix_db_user_extra_info_created_at'), table_name='db_user_extra_info')
    op.drop_table('db_user_extra_info')
    # ### end Alembic commands ###
