"""update db

Revision ID: 8929b363f36d
Revises: 68d0b8738895
Create Date: 2021-07-10 09:51:05.916453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8929b363f36d'
down_revision = '68d0b8738895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_user_extra_info', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('db_user_extra_info', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('db_user_extra_info', sa.Column('following', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_user_extra_info', 'following')
    op.drop_column('db_user_extra_info', 'bio')
    op.drop_column('db_user_extra_info', 'avatar')
    # ### end Alembic commands ###
