"""init db

Revision ID: 9fbe05d43a8f
Revises: 588cca5b1c70
Create Date: 2021-07-03 21:52:43.148566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fbe05d43a8f'
down_revision = '588cca5b1c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_item',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_item_created_at'), 'db_item', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_item_deleted'), 'db_item', ['deleted'], unique=False)
    op.create_index(op.f('ix_db_item_description'), 'db_item', ['description'], unique=False)
    op.create_index(op.f('ix_db_item_title'), 'db_item', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_item_title'), table_name='db_item')
    op.drop_index(op.f('ix_db_item_description'), table_name='db_item')
    op.drop_index(op.f('ix_db_item_deleted'), table_name='db_item')
    op.drop_index(op.f('ix_db_item_created_at'), table_name='db_item')
    op.drop_table('db_item')
    # ### end Alembic commands ###
