"""update db

Revision ID: c7a3ca9a96f9
Revises: 77e91aff819b
Create Date: 2021-07-10 09:48:15.340766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a3ca9a96f9'
down_revision = '77e91aff819b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_user', sa.Column('username', sa.String(), nullable=False))
    op.drop_index('ix_db_user_full_name', table_name='db_user')
    op.create_index(op.f('ix_db_user_username'), 'db_user', ['username'], unique=True)
    op.drop_column('db_user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_db_user_username'), table_name='db_user')
    op.create_index('ix_db_user_full_name', 'db_user', ['full_name'], unique=False)
    op.drop_column('db_user', 'username')
    # ### end Alembic commands ###
