"""init db

Revision ID: ca85dbb1e5c2
Revises: 0c22580da24b
Create Date: 2021-07-03 21:46:45.501269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca85dbb1e5c2'
down_revision = '0c22580da24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
